version: "3"

services:
  db:
    image: postgres:10
    container_name: db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    env_file:
      - .env

  app:
    build: .
    container_name: app
    tty: true
    command:
      /bin/sh -c
      "dockerize -wait tcp://db:5432 &&
      pipenv install --system --dev &&
      python3 manage.py migrate &&
      python3 manage.py loaddata blog/fixtures/init.json &&
      python3 manage.py loaddata sushi/fixtures/init.json &&
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code。
    ports:
      - "8000:8000"
    working_dir: "/code/app"
    env_file:
      - .env
    depends_on:
      - db